# Generated by Django 5.2 on 2025-04-21 13:13

from django.db import migrations, models

def create_initial_parts(apps, schema_editor):
    Part = apps.get_model('parts', 'Part')

    Part.objects.create(
        name='Heavy coil',
        sku='SDJDDH8223DHJ',
        description='Tightly wound nickel-gravy alloy spring',
        weight_ounces=22,
        is_active=True
    )

    Part.objects.create(
        name='Reverse lever',
        sku='DCMM39823DSJD',
        description='Attached to provide inverse leverage',
        weight_ounces=9,
        is_active=False
    )

    Part.objects.create(
        name='Macrochip',
        sku='OWDD823011DJSD',
        description='Used for heavy-load computing',
        weight_ounces=2,
        is_active=True
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=1024)),
                ('weight_ounces', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(create_initial_parts),
    ]
